name: surfclass_dev
channels:
  - conda-forge
dependencies:
  - python=3.7
  - gdal=3.*
  - python-pdal=2.*
  - scikit-learn>=0.21.3
  - scipy
  - black
  - pytest
  - pytest-clarity
  - pylint
  - pip
