version: 2.1
jobs: 
  lint_test_py37_conda:
    docker:
      - image: continuumio/miniconda3
    steps:
    - checkout
    - run:
        name: Install requirements
        command: | 
          conda env create -q -f environment.yml
          # pip install -r requirements.txt
          # pip install black
    - run:
        name: Install Surfclass Package
        command: | 
          source /opt/conda/etc/profile.d/conda.sh
          conda activate surfclass
          pip install .[dev]
    - run:
        name: Run unit tests
        command: |
          source /opt/conda/etc/profile.d/conda.sh
          conda activate surfclass
          pytest ./tests
    - run:
        name: Lint with black
        command: |
          source /opt/conda/etc/profile.d/conda.sh
          conda activate surfclass
          black --check --diff .
       
workflows:
  lint_and_test:
    jobs:
      - lint_test_py37_conda # Always run this, also in branches