version: 2.1
jobs: 
  lint_test_py37_conda:
    docker:
      - image: continuumio/miniconda3
    steps:
    - checkout
    - run:
        name: Create and activate conda environment
        command: |
          conda env create -f environment.yml
    - run:
        name: Install Surfclass Package
        command: | 
          activate surfclass
          pip install .
    - run:
        name: Run unit tests
        command: |
          activate surfclass
          pytest ./tests
       
workflows:
  lint_and_test:
    jobs:
    - lint_test_py37_conda:
        filters:
          branches:
            only:
            - circleci-setup